//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project14.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class table_Order
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public table_Order()
        {
            this.table_OrderDetail = new HashSet<table_OrderDetail>();
            this.table_PaymentLog = new HashSet<table_PaymentLog>();
            this.table_ShipmentLog = new HashSet<table_ShipmentLog>();
        }
    
        public int OrderId { get; set; }
        public Nullable<System.Guid> OrderGuid { get; set; }
        public Nullable<int> MemberId { get; set; }
        public Nullable<System.DateTime> OrderDate { get; set; }
        public string Receiver { get; set; }
        public string Email { get; set; }
        public string Address { get; set; }
        public Nullable<decimal> TotalAmount { get; set; }
        public Nullable<int> UserId { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public Nullable<bool> IsConfirmed { get; set; }
    
        public virtual table_Member table_Member { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<table_OrderDetail> table_OrderDetail { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<table_PaymentLog> table_PaymentLog { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<table_ShipmentLog> table_ShipmentLog { get; set; }
    }
}
