//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project14.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class table_Product
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public table_Product()
        {
            this.table_OrderDetail = new HashSet<table_OrderDetail>();
            this.table_ShoppingCart = new HashSet<table_ShoppingCart>();
        }
    
        public int ProductId { get; set; }
        public string ProductName { get; set; }
        public decimal Price { get; set; }
        public int Stock { get; set; }
        public Nullable<int> CategoryId { get; set; }
        public int Id { get; set; }
        public string Name { get; set; }
        public string Image { get; set; }
    
        public virtual table_Category table_Category { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<table_OrderDetail> table_OrderDetail { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<table_ShoppingCart> table_ShoppingCart { get; set; }
    }
}
